## Analisis de Componentes principales PCA



Clasificar  estudiantes: con necesidades especiales(2) regulares(1) utilizando caracteristicas como: edad, grado y calificacion. Esto permitira definir si un alumno debe recibir atencion especial



In [1]:
#Manejo de datos
import pandas as pd

#Manejo de matrices
import numpy as np

#Graficas
import matplotlib.pyplot as plt

#Algoritmo
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


In [6]:
df=pd.read_csv("estudiantes.csv")
df

Edad  Grado  Calificacion  Desempeno
0     13      1             7          1
1     13      3             3          1
2     14      2             4          1
3     12      1            10          1
4     14      3             2          1
..   ...    ...           ...        ...
95    16      2             4          1
96    15      1             2          1
97    12      1             6          1
98    15      3             6          1
99    16      1             0          1

[100 rows x 4 columns]

In [7]:
#Seleccion de caracteristicas para PCA
x=df.iloc[:,0:3].values
x

array([[13,  1,  7],
       [13,  3,  3],
       [14,  2,  4],
       [12,  1, 10],
       [14,  3,  2],
       [12,  3,  9],
       [13,  1,  4],
       [13,  1,  3],
       [13,  1,  1],
       [15,  1,  9],
       [14,  3,  4],
       [15,  2,  2],
       [16,  1,  5],
       [16,  2,  6],
       [13,  2,  2],
       [15,  1,  5],
       [15,  3,  5],
       [12,  3,  0],
       [15,  2, 10],
       [12,  1,  4],
       [13,  3,  8],
       [12,  3,  6],
       [12,  3,  5],
       [16,  3,  4],
       [13,  3,  5],
       [16,  3,  1],
       [16,  2,  8],
       [15,  2,  3],
       [16,  1,  3],
       [15,  2,  5],
       [13,  1,  1],
       [12,  1,  4],
       [15,  2,  3],
       [13,  2,  0],
       [14,  2,  3],
       [14,  3,  4],
       [16,  2,  4],
       [13,  2,  0],
       [14,  3,  9],
       [16,  2,  9],
       [13,  1,  9],
       [14,  1,  7],
       [13,  1,  2],
       [12,  3, 10],
       [16,  3,  6],
       [16,  1,  2],
       [16,  3,  0],
       [13,  

In [11]:
std=StandardScaler(with_mean=True,with_std=True)
xst=std.fit_transform(x)
xst

array([[-0.76876603, -1.23729565,  0.57316234],
       [-0.76876603,  1.18877425, -0.60861568],
       [-0.05694563, -0.0242607 , -0.31317117],
       [-1.48058644, -1.23729565,  1.45949585],
       [-0.05694563,  1.18877425, -0.90406018],
       [-1.48058644,  1.18877425,  1.16405135],
       [-0.76876603, -1.23729565, -0.31317117],
       [-0.76876603, -1.23729565, -0.60861568],
       [-0.76876603, -1.23729565, -1.19950469],
       [ 0.65487477, -1.23729565,  1.16405135],
       [-0.05694563,  1.18877425, -0.31317117],
       [ 0.65487477, -0.0242607 , -0.90406018],
       [ 1.36669517, -1.23729565, -0.01772667],
       [ 1.36669517, -0.0242607 ,  0.27771783],
       [-0.76876603, -0.0242607 , -0.90406018],
       [ 0.65487477, -1.23729565, -0.01772667],
       [ 0.65487477,  1.18877425, -0.01772667],
       [-1.48058644,  1.18877425, -1.49494919],
       [ 0.65487477, -0.0242607 ,  1.45949585],
       [-1.48058644, -1.23729565, -0.31317117],
       [-0.76876603,  1.18877425,  0.868

In [12]:
#Ejecucion del algoritmo
pca=PCA(n_components=2)
xpca=pca.fit_transform(xst)
xpca

array([[-1.47310356e+00, -5.18828161e-01],
       [ 5.55618312e-01,  1.00104459e+00],
       [ 1.37235343e-01, -1.33849971e-01],
       [-2.41687950e+00,  1.08075614e-01],
       [ 1.15159628e+00,  6.26086404e-01],
       [-9.09854570e-01,  2.00586675e+00],
       [-9.51406617e-01, -8.96746545e-01],
       [-7.77507634e-01, -1.02271934e+00],
       [-4.29709669e-01, -1.27466493e+00],
       [-9.76743556e-01, -7.64853350e-01],
       [ 8.03798316e-01,  8.78031994e-01],
       [ 9.07112295e-01, -6.34780950e-01],
       [ 1.40931361e-01, -1.51772992e+00],
       [ 6.33595352e-01, -3.79875160e-01],
       [ 6.29543213e-02, -1.36810171e-01],
       [-2.81147626e-01, -1.26874453e+00],
       [ 1.05197832e+00,  7.55019399e-01],
       [ 6.55236273e-01,  8.72111593e-01],
       [-4.84079565e-01,  3.73001409e-01],
       [-1.37348560e+00, -6.47761156e-01],
       [-3.13876601e-01,  1.63090856e+00],
       [-3.88157623e-01,  1.62794836e+00],
       [-2.14258640e-01,  1.50197557e+00],
       [ 1.

In [14]:
#Efectividad del PCA
print(pca.explained_variance_ratio_)
print(np.sum(pca.explained_variance_ratio_))


[0.41175439 0.29944488]
0.7111992632992656


In [15]:
#Graficacion
plt.scatter(xpca[:,0],xpca[:,1])
plt.xlabel("Componente1")
plt.xlabel("Componente2")
plt.show()